name: Auto-merged

on:
  pull_request:
    branches:
      - 'main'

jobs:
  dependabot:
    name: 'Dependabot'
    # needs: [build, e2e]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: '${{ secrets.TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: |
          echo ${{ toJson(steps.metadata) }}
          echo ${{ toJson(github.event) }}
        # if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'rails') && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        # run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}