name: Dev Deploy

on:
  pull_request:
    branches:
      - main
  # schedule:
  #   # https://crontab.guru/#0_13_*_*_TUE
  #   - cron: "20 23 * * *"

# concurrency:
#   group: deploy
#   cancel-in-progress: true

jobs:
  Get-Commit:
    runs-on: ubuntu-latest
    environment:
      name: TEST
      
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Generate Release Notes

        id: myRequest
        uses: actions/github-script@v6
        # env:
        #   GITHUB_TOKEN: ${{ secrets.Token }}
        with: 
          github-token: ${{ secrets.PAT }}
          debug: true
          script: |
              try {
                const result = await github.rest.repos.generateReleaseNotes({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: 'unique'
                })
                console.log(result)
                return result.data.body
              } catch (error) {
                return error
              }

          # uses: cardinalby/git-get-release-action@v1
        # uses: mikepenz/release-changelog-builder-action@v3.3.0
        # uses: scottbrenner/generate-changelog-action@master
        # env:
        #   GITHUB_TOKEN: ${{ secrets.Token }}
        # with:
        #   latest: true
        # run: |
        #   curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.Token }}" https://api.github.com/repos/erwincen/workflow/releases/generate-notes -d '{"tag_name":"v1.0.0"}'" https://api.github.com/repos/erwincen/workflow/releases/generate-notes -d '{"tag_name":"v1.0.0"}' -o test.json

      # - name: read workspace body
      #   id: workspace 
      #   run: echo "::set-output name=body::$(test.json)"

      - name: Show Response
        run: echo ${{ steps.myRequest }}

      - name: Show Response 2
        run: echo ${{ toJSON(steps.myRequest)}}

      # - name: print workspace id
      #   run: echo ${{ toJSON(steps.release_notes) }}
      # - name: parse-release-notes
      #   run: echo ${{ toJson(steps.release_notes.outputs) }}

      # - name: Create Release
      #   # if: contains(steps.release_notes.outputs.body, 'fix:')
      #   # https://github.com/softprops/action-gh-release dd
      #   uses: softprops/action-gh-release@v1
      #   with: 
      #     generate_release_notes: true
      #     tag_name: "releases/${{ steps.date.outputs.date }}"
      #     token: "${{ secrets.TOKEN }}"
      #     draft: true

  # Deploy-Stage:
  #   needs: Get-Commit
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: TEST
  #   steps:
  #     - name: deploy_stage
  #       run: echo deploy to stage
   
  # Notify-Stage:
  #   needs: Deploy-Stage
  #   environment:
  #     name: TEST
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: notify CS
  #       uses: slackapi/slack-github-action@v1.21.0
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  #       with:
  #         payload: '{ "text": "1221" }'


  # Deploy-Prod:
  #   needs: Deploy-Stage
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: Prod
  #   steps:
  #     - name: notify CS
  #       run: echo maintenance started
  #     - name: deploy_Prod
  #       run: echo deploy to Prod
   
  # Notify-Prod:
  #   needs: Deploy-Prod
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: notify_Prod
  #       run: echo notify to Prod
  #     - name: notify CS
  #       run: echo maintenance completed
  #     - name: notify CS
  #       uses: slackapi/slack-github-action@v1.21.0
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       with:
  #         payload: '{ "message": ":tada: Deployed to Prod :tada:" }'


# name: Cron

# on:
#   schedule:
# https://crontab.guru/#0_13_*_*_TUE
#     - cron: "0 13 * * TUE"

# jobs:
#   cron:
#     runs-on: ubuntu-latest
    
#     steps:
#       # Runs a single command using the runners shell
#       - name: condition 1
#         if: contains(github.event.head_commit.message, 'fix')
#         run: echo Hello, world!
#       - name: condition 2
#         run: echo github.event.head_commit.message

# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: google-github-actions/release-please-action@v3
#         with:
#           release-type: node
#           package-name: release-please-action