name: Dev Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  Get-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Generate Release Notes
        id: release_notes
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Read-release
        run: echo ${{ github.sha }}

      - name: Create Release
        if: contains(steps.release_notes.outputs.body, 'fix:')

        # uses: ncipollo/release-action@v1
        # with:
        #   tag: releases/test4
        #   generateReleaseNotes: true
        #   token: ${{ secrets.TOKEN }}
        #   draft: true
        #   artifacts: *.

        # uses: "marvinpinto/action-automatic-releases@latest"
        # with:
        #   repo_token: "${{ secrets.TOKEN }}"
        #   draft: true
        #   automatic_release_tag: "releases/${{ steps.date.outputs.date }}"


        uses: softprops/action-gh-release@v1
        with: 
          generate_release_notes: true
          # tag_name: "releases/${{ steps.date.outputs.date }}"
          tag_name: "releases/softprops"
          token: "${{ secrets.TOKEN }}"
          draft: true
          # files: |
          #   Release.txt
          #   LICENSE



        # run: echo good
      # - name: teester
      #   run: echo ${{ toJson(steps.release_notes.outputs.body) }}
      # - name: teester2
      #   run: echo ${{ toString(steps.release_notes.outputs.body) }}
        
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Extract release notes
      #   id: build_changelog
      #   uses: mikepenz/release-changelog-builder-action@{latest-release}
      # - name: condition-1
      #   run: echo ${{steps.build_changelog.outputs.changelog}}

# name: Cron

# on:
#   schedule:
#     - cron: "*/2 * * * *"

# jobs:
#   cron:
#     runs-on: ubuntu-latest
    
#     steps:
#       # Runs a single command using the runners shell
#       - name: condition 1
#         if: contains(github.event.head_commit.message, 'fix')
#         run: echo Hello, world!
#       - name: condition 2
#         run: echo github.event.head_commit.message

# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: google-github-actions/release-please-action@v3
#         with:
#           release-type: node
#           package-name: release-please-action