name: Dev Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  Get-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: condition-1
        run: echo ${{ github.event.commits }}

# name: Cron

# on:
#   schedule:
#     - cron: "*/2 * * * *"

# jobs:
#   cron:
#     runs-on: ubuntu-latest
    
#     steps:
#       # Runs a single command using the runners shell
#       - name: condition 1
#         if: contains(github.event.head_commit.message, 'fix')
#         run: echo Hello, world!
#       - name: condition 2
#         run: echo github.event.head_commit.message

# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: google-github-actions/release-please-action@v3
#         with:
#           release-type: node
#           package-name: release-please-action